apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "$schema": "https://www.krakend.io/schema/v3.json",
      "version": 3,
      "name": "API Gateway",
      "cache_ttl": "3600s",
      "timeout": "60s",
      "log_level": "TRACE",
      "debug_endpoint": true,
      "security/cors": {
        "allow_origins": ["*"],
        "allow_methods": ["POST", "GET"],
        "allow_headers": ["Origin", "Authorization", "Content-Type"],
        "expose_headers": ["Content-Length"],
        "max_age": "12h"
      },
      "endpoints": [
        {
          "endpoint": "/debug",
          "cache_ttl": "1s",
          "backend": [
            {
              "host": [
                "http://krakend:8000"
              ],
              "url_pattern": "/__debug/debug"
            }
          ]
        },
        {
          "endpoint": "/appshell",
          "output_encoding": "no-op",
          "cache_ttl": "1s",
          "headers_to_pass": ["*"],
          "input_headers": ["*"],
          "backend": [
            {
              "host": [
                "http://pulseui-appshell:8080"
              ],
              "output_encoding": "no-op",
              "extra_config": {
                "headers_to_pass":["*"]
              },
              "url_pattern": "/appshell/#/authcallback&state=6f301738-2080-40d3-9e74-5275fc844764"
            }
          ]
        },
        {
          "endpoint": "/pulse_auth",
          "output_encoding": "no-op",
          "cache_ttl": "1s",
          "headers_to_pass": ["*"],
          "input_headers": ["*"],
          "backend": [
            {
              "host": [
                "http://pulseui-appshell:8080"
              ],
              "output_encoding": "no-op",
              "extra_config": {
                "headers_to_pass":["*"]
              },
              "url_pattern": "http://localhost:8081/pulse_auth/signin?redirect=http://localhost:8081/appshell/#/authcallback&state=01ce89fb-c544-4423-ad98-77224b900613/signin?redirect=http//localhost8080/appshell/authcallback&state=01ce89fb-c544-4423-ad98-77224b900613"
            }
          ]
        },
        {
          "endpoint": "/graphs",
          "method": "GET",
          "cache_ttl": "1s",
          "headers_to_pass": ["*"],
          "input_headers": ["*"],
          "extra_config": {
            "headers_to_pass":["*"],
            "auth/validator":{
              "alg": "RS256",
              "jwk_url": "http://keycloak:8080/auth/realms/irispulse/protocol/openid-connect/certs",
              "disable_jwk_security": true,
              "operation_debug": true
            }
          },
          "backend": [
            {
              "host": ["http://workflowgraph:8080"],
              "extra_config": {"headers_to_pass":["*"]},
              "url_pattern": "/workflow/681cb7acfd4e9602e71ff364/graphs"
            }
          ]
        },
        {
          "endpoint": "/certs",
          "method": "GET",
          "cache_ttl": "1s",
          "headers_to_pass": ["*"],
          "input_headers": ["*"],
          "extra_config": {
            "headers_to_pass":["*"],
            "auth/validator":{
              "alg": "RS256",
              "jwk_url": "http://keycloak:8080/auth/realms/irispulse/protocol/openid-connect/certs",
              "disable_jwk_security": true,
              "operation_debug": true
            }
          },
          "backend": [
            {
              "host": [
                "http://keycloak:8080"
              ],
              "extra_config": {
                "headers_to_pass":["*"]
              },
              "url_pattern": "/auth/realms/irispulse/protocol/openid-connect/certs"
            }
          ]
        }       
      ]
    }
---
# keycloak-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: docker.irisxtract.com/pulse/pulse-api-gateway:0.0.1
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 250Mi
              cpu: 100m
            limits:
              memory: 250Mi
              cpu: 2000m
          volumeMounts:
            - mountPath: /etc/krakend/krakend.json
              name: krakend-config
              subPath: krakend.json
          imagePullPolicy: IfNotPresent
          command: [ "/usr/bin/krakend" ]
          args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8000"]
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
---
# kraken-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: krakend
spec:
  selector:
    app: krakend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP  # Use ClusterIP for internal access